name: pyssembly
description: Python to Assembly (MASM 32) compiler.
version: 0.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  stack: ^0.2.1
  test: ^1.19.5
  tuple: ^2.0.0


dev_dependencies:
  lints: ^1.0.0
